== Title of First Chapter

This is a paragraph of text, including *bold* and _italic_ text. Also [line-through]#strikethrough#.

This includes `+code+` identifiers, and some "quoted text" (including 'single quotes').

This is an inline URL: https://lurklurk.org[https://lurklurk.org]

This is https://github.com/daviddrysdale/mdbook-docbook[link].

[quote]
This is a block quote, including
multiple lines.

A paragraph that includes HTML characters – like an en-dash.

Scott Meyers' original _Effective C&plus;&plus;_ series.  The C&plus;&plus; language was (and is) full of footguns, so _Effective
C&plus;&plus;_ focused on a collection of advice.

[source,rust]
----
fn main() {
}
----

Now for some bullets:

* top-level first
** second-level 1
** second-level 2
*** third level
* top-level second
[arabic]
.. sub-numbered bullet 1
.. sub-numbered bullet 2
* top-level third
+
with follow-on para
* top-level fourth.

A MarkDown table.

[cols="1,<1,^1,>1"]
|===
| Heading 1| Heading 2| Heading 3| Hdr 4

| normal| left-align| center| right

| `+code+`| http://example.com[link]| | left _blank_
|===

List with checkboxes:

* [ ] Do something.
* [x] Do something else.
